### ISSUE TITLE
Remove config from scheduler.js

### ISSUE THREAD

**Issue by eugk** [radekk/webtask-mfa-monitor#2]
It would be good to remove the URL and token config from scheduler.js, to make code updates easier, and to prevent accidental checkin of these values.

**Comment by radekk** [comment]
I was thinking about it, how to remove those variables from scheduler.js and still keep them in a one file. I've a draft solution ready by using ``build`` process to generate scheduler.js from a template file as well as ``configuration`` script for the whole process.

It looks as follow:

- Running configuration process from the terminal - ``gulp configure``
 - Get data from a user: webtask token, tokens for monitors (github) and notifiers (slack)
 - Issue a token for every webtask using webtask.io API or wt-cli module
 - Put issued tokens into a template
 - Generate configuration files for every webtask (different config for different webtasks, i.e. Slack requires token and channel whereas github requieres token and organization name).
 - Generate ``scheduler.js`` ready for a cron task
- Running build proccess - ``gulp build``
 - Create cron task using generated scheduler script


I'll keep you updated.

**Comment by radekk** [comment]
Now it's solved. No more configuration dependencies inside source code. More information here: #3
